# Generated by Django 4.2.7 on 2023-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.IntegerField()),
                ('conf_senha', models.CharField(max_length=128)),
            ],
        ),
    ]
